start:
  description: Start cooking a profile.
  fields:
    profile:
      description: Profile data which describes the temperature curve.
      example: 01060500000008090c000c00060000001200000002aa0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000280a0f260300915573000000008278736e001000756e0028050075826e002810ff75266e0228100069005a00b2e6
      required: true
      selector:
        text:
    duration:
      description: Cooking duration in minutes. Will only be applied for profiles that allow it.
      example: 120
      required: false
      selector:
        duration:
      #   number:
      #     min: 0
      #     max: 1440
      #     unit_of_measurement: "min"
    schedule:
      description: Time in minutes until the cooking should be finished
      example: 180
      required: false
      selector:
        datetime:
        # number:
        #   min: 0
        #   max: 1440
        #   unit_of_measurement: "min"
    auto_keep_warm:
      description: Keep warm after cooking?
      required: false
      selector:
        boolean:
    taste:
      description: Rice hardness
      required: false
      selector:
        select:
          mode: dropdown
          options:
            - label: Soft
              value: 0
            - label: Moderate
              value: 1
            - label: Rigid
              value: 2

stop:
  description: Stop the cooking process.

